#!/bin/bash

# Directory containing your wallpapers
WALLPAPERS_DIR="/home/kuroneko/Pictures/wallpapers"

# Get list of wallpapers
wallpapers=$(ls "$WALLPAPERS_DIR")

# Select wallpaper using dmenu
selected_wallpaper=$(echo "$wallpapers" | dmenu -p "Choose wallpaper: " -l 7)

# Set selected wallpaper
wal -i "$WALLPAPERS_DIR/$selected_wallpaper"
